In [1]:
import numpy as np

Ejericio NumPy

In [2]:
edades = np.random.uniform(
    size=(3,3),
    low=22,
    high=60
    ).round()
edades

array([[42., 36., 25.],
       [57., 38., 48.],
       [37., 56., 58.]])

In [3]:
ingresos = np.random.uniform(
    size=(3,3),
    low=2,
    high=5
    ).round(decimals=3)*1e3
ingresos

array([[4622., 3873., 2905.],
       [4951., 2593., 3176.],
       [4704., 3623., 3471.]])

In [4]:
union = np.stack([edades,ingresos], axis=2).reshape(9,2)
union

array([[  42., 4622.],
       [  36., 3873.],
       [  25., 2905.],
       [  57., 4951.],
       [  38., 2593.],
       [  48., 3176.],
       [  37., 4704.],
       [  56., 3623.],
       [  58., 3471.]])

In [5]:
mayor_que = union >= [20,2e3]
menor_que = union <= [30,5e3]
filtro = np.logical_and(mayor_que,menor_que)
filtro

array([[False,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True]])

In [6]:
filtro_def = np.logical_and.reduce(filtro,1)
filtro_def

array([False, False,  True, False, False, False, False, False, False])

In [7]:
res = union[filtro_def]
res 

array([[  25., 2905.]])